Repository WingedSeal/jmc, pull requests merged in 2023-09, with the labels that each got.

#34 Support multiline strings in JSON
  src/jmc/compile/command/jmc_function.py
  src/jmc/compile/compiling.py
  src/jmc/compile/lexer.py
Labels: Status: Accepted, Type: Feature change, Priority: Low

#35 Separator
  src/jmc/compile/command/builtin_function/load_only.py
  src/jmc/compile/command/utils.py
  src/tests/test_all.py
Labels: Type: Feature change, Priority: Medium, Status: Change needed

#37 Improve webpage docs
  src/pages/BuiltInFunction/Features.tsx
  src/pages/BuiltInFunction/HowTo.tsx
  src/pages/FlowControls/FlowControls.tsx
Labels: Type: Documentation, Status: Accepted, Priority: Low

#38 O(1) switch
  src/jmc/compile/command/_flow_control.py
  src/jmc/compile/command/builtin_function/execute_excluded.py
  src/jmc/compile/exception.py
  src/jmc/terminal/configuration.py
  src/jmc/terminal_commands.py
Labels: Status: Accepted, Type: Feature change, Priority: Medium
