Repository WingedSeal/jmc, pull requests merged in 2023-11, with the labels that each got.

#61 Error suggestion for misspelled built-in func name
  src/jmc/compile/lexer_func_content.py
Labels: Status: Accepted, Type: Feature change, Priority: Low

#60 Suggestion in error for wrong JSON file type
  src/jmc/compile/lexer.py
Labels: Status: Accepted, Type: Feature change, Priority: Low

#57 Give hint if built-in func parameter ends with `()`
  src/jmc/compile/utils.py
Labels: Status: Accepted, Type: Feature change, Priority: Low

#54 Update README.md
  README.md
Labels: Type: Documentation, Status: Accepted, Priority: Low

#58 Subcommand fixes
  src/jmc/compile/lexer_func_content.py
Labels: Status: Accepted, Type: Fix bug, Priority: High

#53 Add `Tag.update()` built-in function
  src/jmc/compile/command/builtin_function/execute_excluded.py
  src/tests/integration/test_jmc_function.py
Labels: Status: Accepted, Type: New feature, Priority: Low

#59 Make custom namespaces work when calling functions
  src/jmc/compile/command/jmc_function.py
  src/jmc/compile/command/var_operation.py
  src/jmc/compile/datapack.py
  src/jmc/compile/decorator_parse.py
  src/jmc/compile/lexer_func_content.py
Labels: Status: Accepted, Type: Fix bug, Priority: High

#62 Prevent duplicate imports when using wildcard
  src/jmc/compile/lexer.py
Labels: Status: Accepted, Type: Fix bug, Priority: Medium

#64 Add `$if` for `execute if` commands w/ macros in them
  src/jmc/compile/command/_flow_control.py
  src/jmc/compile/command/flow_control.py
  src/jmc/compile/lexer.py
  src/jmc/compile/lexer_func_content.py
Labels: Status: Accepted, Type: New feature, Priority: Low

#63 Implement `extends` keyword
  src/jmc/compile/lexer.py
  src/jmc/compile/utils.py
Labels: Status: Accepted, Type: New feature, Priority: Low

#66 Add `Bossbar.setName`
  src/jmc/compile/command/builtin_function/jmc_command.py
Labels: Status: Accepted, Type: New feature, Priority: Low

#65 Add `#bind __namehash16__`
  src/jmc/compile/header_parse.py
Labels: Status: Accepted, Type: New feature, Priority: Low

#67 Fix bug with `extend`ing a JSON file from another class
  src/jmc/compile/lexer.py
Labels: Status: Accepted, Type: Fix bug, Priority: Medium
