Repository WingedSeal/jmc, pull requests merged in 2023-12, with the labels that each got.

#68 Update docs
  src/pages/BuiltInFunction/Features.tsx
  src/pages/FlowControls/FlowControls.tsx
Labels: Type: Documentation, Status: Accepted, Priority: Medium

#69 Update JSON-related stuff for Minecraft 1.20.3
  src/jmc/compile/command/builtin_function/jmc_command.py
  src/jmc/compile/command/utils.py
Labels: Status: Accepted, Type: Fix bug, Priority: Medium

#70 Properly insert NBT `source` key on post 1.20.3
  src/jmc/compile/command/utils.py
Labels: Status: Accepted, Type: Fix bug, Priority: Low

#71 Object.isEqual() & String.isEqual() dont require `type` argument now
  src/jmc/compile/command/builtin_function/bool_function.py
Labels: Status: Accepted, Type: Feature change, Priority: Low
